packages:
  - 'shared'
  - 'contracts/velum'
  - 'backend'
  - 'frontend'
allowBuilds:
  '@swc/core': false
  classic-level: false
  esbuild: true
  msgpackr-extract: true
  sharp: set this to true or false
  unrs-resolver: true
